name: DAG checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'
        architecture: 'x64'
      
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        pip install --upgrade pip
        pip install apache-airflow==1.10.15 requests
      
    - name: Initialize Airflow database
      env:
        AIRFLOW_HOME: ./airflow
      run: airflow initdb
      
    - name: Start Airflow scheduler and webserver
      env:
        AIRFLOW_HOME: ./airflow
      run: |
        nohup airflow scheduler > logs/scheduler.log &
        sleep 5
        nohup airflow webserver > logs/webserver.log &

    - name: Run DAG
      env:
        AIRFLOW_HOME: ./airflow
      run: airflow dags test airflow_tasks
