name: Airflow Check

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        sudo apt-get install -y libssl-dev
        sudo apt-get install -y libffi-dev
        sudo apt-get install -y python3-dev

    - name: Install Airflow
      run: |
        python -m pip install --upgrade pip
        pip install apache-airflow==1.10.15 --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-1.10.15/constraints-3.8.txt"

    - name: Initialize Airflow database
      run: airflow initdb
      env:
        AIRFLOW_HOME: ./airflow
